name: 哔咔漫画自动打哔咔

on:
    workflow_dispatch:
    schedule:
        - cron: "00 16 * * *"
        #- cron: "00 00 * * *"
    watch:
        types: [started]

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - name: 查看
              uses: actions/checkout@v2

            - name: "初始化Python"
              uses: actions/setup-python@v1
              with:
                python-version: 3.8

            - name: "安装依赖包"
              run: pip install -r ./requirements.txt

            - name: "运行 哔咔漫画自动打哔咔"
              run: python3 function/bika/bika.py
              env:
                  BIKA_USER: ${{ secrets.BIKA_USER }}
                  BIKA_PASS: ${{ secrets.BIKA_PASS }}
                  SEND_KEY: ${{ secrets.SEND_KEY }}
                  PUSH_KEY: ${{ secrets.PUSH_KEY }}
                  BARK_PUSH: ${{ secrets.BARK_PUSH }}
                  PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN}}
                  PUSH_PLUS_USER: ${{ secrets.PUSH_PLUS_USER}}
                  TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
                  TG_USER_ID: ${{ secrets.TG_USER_ID }}
                  BARK_SOUND: ${{ secrets.BARK_SOUND }}
                  DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
                  DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
                  QYWX_AM: ${{ secrets.QYWX_AM}}

            - name:  ${{ env.CACHE_NAME }}
            #- name: 缓存 Pip 模块
              uses: actions/cache@v2
              env:
                CACHE_NAME:  缓存 Pip 模块
              with:
                # This path is specific to Ubuntu
                path: ~/.cache/pip
                # Look to see if there is a cache hit for the corresponding requirements file
                key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
                restore-keys: |
                  ${{ runner.os }}-pip-
                  ${{ runner.os }}-
#最后推送 2021年5月19日
